language: php

env:
    global:
        - MIN_PHP=5.5.9
        - SYMFONY_PROCESS_PHP_TEST_BINARY=~/.phpenv/versions/5.6/bin/php

matrix:
    include:
        # Use the newer stack for HHVM as HHVM does not support Precise anymore since a long time and so Precise has an outdated version
        - php: hhvm-3.12
          sudo: required
          dist: trusty
          group: edge
        - php: 5.5
        - php: 5.6
        - php: 7.0
          env: deps=high
        - php: 7.0
          env: deps=low
    fast_finish: true

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - PHP=$TRAVIS_PHP_VERSION
    - if [[ $PHP != hhvm* ]]; then phpenv config-rm xdebug.ini; fi
    - composer selfupdate
    # Matrix lines for intermediate PHP versions are skipped for pull requests
    - if [[ ! $deps && ! $PHP = ${MIN_PHP%.*} && ! $PHP = hhvm* && $TRAVIS_PULL_REQUEST != false ]]; then deps=skip; skip=1; fi
    # A sigchild-enabled-PHP is used to test the Process component on the lowest PHP matrix line
    - if [[ ! $deps && $PHP = ${MIN_PHP%.*} && ! -d php-$MIN_PHP/sapi ]]; then wget http://museum.php.net/php5/php-$MIN_PHP.tar.bz2 -O - | tar -xj; (cd php-$MIN_PHP; ./configure --enable-sigchild --enable-pcntl; make -j2); fi
    - if [[ ! $PHP = hhvm* ]]; then INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; else INI_FILE=/etc/hhvm/php.ini; fi

install:
    - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS
    - if [[ ! $PHP = hhvm* ]]; then php -i; else hhvm --php -r 'print_r($_SERVER);print_r(ini_get_all());'; fi

script:
     phpunit

notifications:
    email: diegoangel77@rocketmail.com
